politylink/politylink-gatsby

src/templates/bill.js

衆議院先議
例：地方交付税法及び特別会計に関する法律の一部を改正する法律案
参議院先議
例：割賦販売法の一部を改正する法律案

POL-22: apply first House

---

gatsby-config.js
src/components/billCard.js
src/components/billCard.module.css
src/components/container.js
src/components/container.module.css
src/components/linkCard.module.css
src/components/minutesCard.module.css
src/pages/index.js
src/templates/bill.js
src/templates/minutes.js

議案詳細ページではBillCardを左づめで配置する。
議案一覧ページでは中央配置のまま。

POL-82: fix bill card position

---

gatsby-node.js
src/components/layout.js
src/components/linkCard.js
src/components/memberCard.js
src/components/progress.js
src/components/seo.js
src/pages/committees.js
src/pages/index.js
src/templates/bill.js
src/templates/committee.js
src/templates/minutes.js
src/utils/constants.js
src/utils/seoutils.js
src/utils/url.js

- 衝突を防ぐためlocalStorageのkeyをまとめて定義する
- GraphQL idからpathを構成するメソッドを切り出す
- 委員会一覧をフッターにも追加する。議員一覧はまだ実装されてないので除く
- PyCharmを使ってファイルをフォーマットし直す
- seo用のdescriptionをまとめて定義する

POL-92: refactor

---

src/components/committeeCard.js
src/components/committeeCard.module.css
src/templates/minutes.js
src/templates/minutes.module.css

POL-88: add belonged to committee card

---

src/templates/bill.js
src/templates/bill.module.css

法律詳細ページにAliasesを追加

---

src/components/billCard.js
src/components/billCard.module.css
src/pages/index.js
src/templates/minutes.js

POL-102: add aliases to BilLCard

---

src/components/newsCard.module.css
src/templates/bill.js
src/templates/bill.module.css
src/templates/minutes.js

POL-123: add NewsCard to bill detail page

---

src/components/billCard.js
src/components/billCard.module.css
src/components/minutesCard.js
src/components/minutesCard.module.css
src/pages/index.js
src/templates/bill.js
src/templates/committee.js

POL-93: add news badge

---

gatsby-node.js
src/templates/timeline.js
src/templates/timeline.module.css

範囲外の日付へ遷移できないように修正
https://politylink.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=POL&modal=detail&selectedIssue=POL-140

POL-140: define invalid date

---

gatsby-config.js
gatsby-node.js
package-lock.json
package.json
src/components/calendar.js
src/pages/timelines.js
src/templates/bill.js
src/templates/committee.js
src/templates/minutes.js
src/templates/timeline.js
src/utils/dateutils.js
src/utils/formatutils.js
src/utils/seoutils.js

* add RSS feed
* move formatDate methods to dateutils

POL-166: add RSS feed

---

package-lock.json
package.json
src/components/calenderTimeline.css
src/components/calenderTimeline.js
src/components/layout.js
src/components/layout.module.css
src/components/menu.js
src/pages/bills.js
src/pages/calender.js
src/utils/constants.js
src/utils/seoutils.js

法律案カレンダーの実装
* 直近の国会に提出された法律案の審議状況を、一覧形式で比較することができます。これにより、審議が早い法律案、滞っている法律案を一目で見つけることができます
特に注意して確認してもらいたい点は
* seoutils の文言について
* 様々な環境でもレイアウトが崩れないかどうか

POL 164: BillCalender

---

gatsby-config.js
package-lock.json
package.json

POL-120: add sitemap.xml

---

src/components/linkCard.module.css
src/components/parentPath.js
src/components/parentPath.module.css
src/components/share.js
src/components/share.module.css
src/components/socialLinks.js
src/components/socialLinks.module.css
src/templates/bill.js
src/templates/committee.js
src/templates/member.js
src/templates/minutes.js
src/utils/formatutils.js

POL-181: add social links in member page

---

package-lock.json
package.json
src/templates/member.js
src/utils/formatutils.js

POL-207: add twitter timeline in Member

---

src/templates/committee.js
src/templates/minutes.js
src/templates/minutes.module.css

POL-214: update committee/minutes page to 2 pane layout

---

src/components/calendar.js
src/pages/timelines.js
src/templates/timeline.js

@kenya-sk POL-160 を修正しましたが、こういう意図であってますか？

POL-160: derive minDate and maxDate from timeline resource

---

src/components/linkCard.js
src/utils/fontawesome.js
src/utils/sortutils.js

POL-254: add url icon types

---

src/templates/minutes.js

Minutes.speakersがあるときは「説明・質疑者」を発言順に表示、ない場合は今まで通り発言者をランダム順に表示

POL-253: use minutes.speakers for MemberCard

---

package.json
src/components/memberCard.js
src/components/memberCard.module.css
src/pages/members.js
src/templates/minutes.js

POL-271: Update memberCard's appearance

---

src/components/billCardV2.js
src/components/billCardV2.module.css
src/components/search.js
src/components/search.module.css
src/pages/bills/index2.js

POL-305: WIP bills/index2

---

src/components/container.js
src/components/minutesCard.js
src/components/progress.js
src/templates/bill.js

Before:
After:
変更点
* 配列の子要素にはユニークな key が必要であるため、それを付けた
* FontAwesomeIcon の設定を修正した

POL-313: add keys on array elements
